---
title: "桃園移工之探討"
author: "衝鋒特戰隊"
date: "2018年5月2日"
output: html_document
---

```{r 環境設定,include=FALSE}
library(dplyr)
library(ggplot2)
library(magrittr)
knitr::opts_chunk$set(fig.showtext=TRUE)
library(showtext)
showtext_auto()
library(plotly)
```

```{r include=FALSE}
FTnumbers <- read.table("/Users/Choumeinmein/Documents/GitHub/econblog-master/86_106FTnumbers.csv", header = TRUE , sep = ",")
FTnumbers %<>% mutate(year=year+1911,
                     ratio=round(foreigner/taiwan*100,2),
                     rateofchange=round(rateofchange,2))
FTnumbers %<>% filter(year>=2002)
```

```{r include=FALSE}
a <- ggplot(FTnumbers, aes(year,rateofchange,size=ratio)) +
  geom_point() +
  labs(x="年份",
       y="",
       title="移工與台灣就業市場關係",
       subtitle="移工較去年增減率(單位：百分比)"
       )+
  theme_minimal()
a
```
```{r echo=FALSE}
plot_ly(FTnumbers,x = ~year,y = ~rateofchange,size = ~ratio,
        hoverinfo = 'text',
        text = ~paste('</br>年份: ', year,
                      '</br> 移工的變動率: ', rateofchange,
                      '</br> 移工與台勞的比例: ', ratio)
        ) %>% 
  layout(showlegend = FALSE,
         title='移工與台灣就業市場關係',
         yaxis = list(title = "移工較去年增減率(單位：百分比)"),
         xaxis = list(title = "年份")
         ) %>%
  rangeslider()
```
```
從缺工人數來看，工業部門主要缺工的行業分別為製造業、營造業，雖然引進外籍勞工，工業部門缺工的人數有在下降，但下降的幅度很有限，原因為二：
1.	申請國際移工的配額有限，來保障國民的工作機會。
2.	台灣勞動者不願從事3K（辛苦、汙穢、危險）產業，不僅環境髒亂、危害性化學物品種類等特性，可能會影響勞工安全與健康，所以大部分廠商都是聘用國際移工來工作。
```
```
【桃園移工對勞動需求的意義】
全台最多移工的地區，分別是桃園、台中、新北，從歷年的數據來看，桃園一直居於首位，將近1/6的移工選擇在桃園就業。細分桃園移工工作的產業類別大多為產業外籍勞工，只有少部分（1/5）的外籍勞工在社福產業工作。
```
```{r include=FALSE}
city2 <- read.table("/Users/Choumeinmein/Documents/GitHub/econblog-master/90_106city2.csv", header = TRUE , sep = ",")
city2 %<>% filter(year>=2010)
```
```{r echo=FALSE}
b <- ggplot(city2,
            aes(year,number, fill = city)
            ) +
  geom_col(stat = "identity"
           ) +
  labs(x="年份",
       y="人數",
       title="移工在台灣的人數",
       subtitle="單位:人"
       ) +
  scale_fill_discrete(name="縣市",
                      breaks=c("Taoyuan","Taichung","NewTaipei","cTaipei","cTainan","Kaohsiung"
                             ,"aothers"),
                      labels=c("桃園市","台中市","新北市","台北市","台南市","高雄市"
                             ,"其他十四縣市")
                      )+
  theme_minimal()
b
```
```{r include=FALSE}
Taoyuan <- read.table("/Users/Choumeinmein/Documents/GitHub/econblog-master/Taoyuan.csv", header = TRUE , sep = ",")
Taoyuan %<>%
  mutate(year=year+1911)%<>%
  filter(year>=2012)
Taoyuan$year <- as.integer(Taoyuan$year)
```
```{r 移工分布產業別,echo=FALSE}
c <- ggplot(Taoyuan,
            aes(x=year,y=number,fill=category)
            )+
  geom_col()+
  labs(x="年份",
       y="人數",
       title="桃園市產業及社服外勞人數",
       subtitle="單位:人")+
  scale_fill_brewer(name="產業別",
                    breaks=c("industry","Socialwelfare"),
                    labels=c("產業外籍勞工","社福外籍勞工")
                    )+
  theme_minimal()
c
```
```
桃園為何那麼多產業移工？主要原因為桃園是全臺第一工業科技大市，臺灣五百大製造業有超過三分之一在桃園設廠，工業產值常居全臺之冠，桃園擁有32個報編工業區，從傳統產業到高科技產業聚落。另外因應「3K行業專案」和2013年新增「外加就業安定費附加外勞數額」更間接的推動廠商多僱用移工。而桃園的外籍勞工主要從事的工作項目多為：三Ｋ行業專案、附加外籍勞工等的製造業產業
```
```{r include=FALSE}
KKK <- read.table("/Users/Choumeinmein/Documents/GitHub/econblog-master/90_106_3k.csv", header = TRUE , sep = ",")
KKK %<>%
  mutate(year=year+1911) %<>%
  filter(year>=2012)
KKK$year <- as.integer(KKK$year)
```
```{r 製造業+其他,echo=FALSE}
d <- ggplot(KKK,
            aes(x=year,y=number,fill=industry)
            )+
  geom_col()+
  labs(x="年份",
       y="人數",
       title="桃園市產業外勞人數",
       subtitle="單位:人")+
  scale_fill_brewer(name="開放項目",
                    breaks=c("KKK","badditional","aothers"),
                    labels=c("3K行業專案","附加外籍勞工","其他")
                    )+
  theme_minimal()
d
```